sonar.projectKey=lerakaplich_Documents
sonar.organization=lerakaplich
sonar.projectName=Documents
sonar.sources=client,server
sonar.sourceEncoding=UTF-8
sonar.python.version=3.13
sonar.exclusions=**/__pycache__/**,**/*.pyc,**/.venv/**,**/venv/**,**/node_modules/**,**/migrations/**